### PR TITLE
PR for Issue #11

### PR DESCRIPTION
**Pull request by akodiakson**
Implemented the new Mobile Vision API FaceDetection feature. 

Based on the isSmilingProbability returned from the API, display an uplifting message to the user based on varying degrees of implied mood.

These include moderately invasive changes to: 
-- AndroidManifest, in that it requires the camera feature and permission. 
-- A new dependency, being Google Play Services Vision API

A new Module for face detection and a placeholder icon (until something more in-line with the current icons) were added,

Inspiration (Stuart Smalley):
https://www.youtube.com/watch?v=-DIETlxquzY

### CODE REVIEW

**Comment by akodiakson** [comment]
This relies on the mounted device's front facing camera not being obscured.

**Comment by Fleker** [comment]
Is the camera obscured when behind the mirror?

**Comment by HannahMitt** [comment]
Thanks for the PR! I actually ran away to Iceland without a computer on Friday, but I'm excited to look into this when I'm back next week.

**Comment by HannahMitt** [comment]
This is really cool. Thanks so much akodiakson

**Comment by akodiakson** [comment]
Awesome, thank you Hannah.

I'd be particularly cautious with anything surrounding an Android camera in terms of stability. Hope it's not intrusive to the physical design of the mirror in terms of the front-facing camera not needing to be blocked.

The mood related messages are cheese-y, so feel free to do something better.

There are some pretty decent use cases that can evolve from this, especially toggling the display visibility when faces are detected.

There's an issue where, if this is the first time the mobile-vision API is used in an app on your device, your app will call out to a remote repo and install some libraries.

Check this out:
http://stackoverflow.com/questions/32099530/google-vision-barcode-library-not-found

Andrew

**Pull request merged**
